name: Test python app
description: Checks if there are any changes in the path

inputs:
  python_version:
    description: Python version
    required: false
    default: "3.11"
  pypi_user:
    description: PyPI user
    required: true
  pypi_password:
    description: PyPI password
    required: true
  rmq_user:
    description: RabbitMQ user
    required: false
    default: ""
  rmq_password:
    description: RabbitMQ password
    required: false
    default: ""
  rmq_hosts:
    description: RabbitMQ hosts
    required: false
    default: ""
  rmq_vhost:
    description: RabbitMQ vhost
    required: false
    default: ""
  postgres_host:
    description: Postgres host
    required: false
    default: ""
  postgres_password:
    description: Postgres password
    required: false
    default: ""
  postgres_db_name:
    description: Postgres database
    required: false
    default: ""
  mongo_db_name:
    description: Mongo database
    required: false
    default: ""
  mongo_connection_string:
    description: Mongo connection string
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v4
    - name: Checkout PR
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install dependencies
      shell: bash
      env:
        PYPI_USER: ${{ inputs.pypi_user }}
        PYPI_PASSWORD: ${{ inputs.pypi_password }}
      run: make install-dev
    - name: Test with pytest
      shell: bash
      env:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
        POSTGRES_DBNAME: ${{ inputs.postgres_db_name }}
        POSTGRES_TEST_DB_NAME: ${{ inputs.postgres_db_name }}
        POSTGRES_HOST: ${{ inputs.postgres_host }}
        POSTGRES_PORT: "5432"
        RMQ_USER: ${{ inputs.rmq_user }}
        RMQ_PASSWORD: ${{ inputs.rmq_password }}
        RMQ_HOSTS: ${{ inputs.rmq_hosts }}
        RMQ_VHOST: ${{ inputs.rmq_vhost }}
        MONGODB_CONNECTION_STRING: ${{ inputs.mongo_connection_string }}
        MONGODB_DBNAME: ${{ inputs.mongo_db_name }}
      run: make test
