name: Build python package
description: Build a python wheel package

inputs:
  version:
    description: Application version
    required: true
  version_path:
    description: Application version path
    required: true
  setup_path:
    description: Application setup.py path
    required: true
  pypi_repository:
    description: PyPI repository
    required: true
  pypi_push_user:
    description: PyPI user
    required: true
  pypi_push_password:
    description: PyPI password
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      shell: bash
      env:
        TWINE_USERNAME: ${{ inputs.pypi_push_user }}
        TWINE_PASSWORD: ${{ inputs.pypi_push_password }}
        TWINE_REPOSITORY_URL: ${{ inputs.pypi_repository }}
      run: |
        echo "__version__ = '${{ inputs.version }}'" > ${{ inputs.version_path }}
        cd ${{ inputs.setup_path }}
        python setup.py sdist bdist_wheel
        twine upload dist/*
