name: Build artefacts

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_dir:
        required: true
        type: string
    outputs:
      tag:
        description: 'Version of the built application'
        value: ${{ jobs.bump_version.outputs.tag }}

jobs:
  check_changes_in_lib:
    runs-on: ubuntu-latest

    outputs:
      modified: ${{ steps.modified.outputs.modified }}

    steps:
      - id: modified
        uses: anna-money/action-check-changes@master
        with:
          path: ${{ inputs.app_dir }}/schema

  bump_version:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.bump.outputs.new_tag }}

    steps:
      - uses: anna-money/action-bump-version@master
        id: bump
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build_lib:
    runs-on: ubuntu-latest
    needs: [ bump_version, check_changes_in_lib ]
    if: ${{ needs.check_changes_in_lib.outputs.modified > 0 }}

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/build-python-package@master
        with:
          version: ${{ needs.bump_version.outputs.tag }}
          version_path: ${{ inputs.app_dir }}/version.py
          setup_path: ${{ inputs.app_dir }}/schema
          pypi_repository: ${{ secrets.PYPI_HOST }}
          pypi_push_user: ${{ secrets.PYPI_PUSH_USERNAME }}
          pypi_push_password: ${{ secrets.PYPI_PUSH_PASSWORD }}

  build_image:
    runs-on: ubuntu-latest

    needs: bump_version

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/build-python-image@master
        with:
          name: ${{ inputs.app_name }}
          version: ${{ needs.bump_version.outputs.tag }}
          version_path: ${{ inputs.app_dir }}/version.py
          registry: ${{ secrets.DOCKER_REGISTY }}
          gcloud_service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          pypi_user: ${{ secrets.PYPI_USER }}
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
