name: Build dev artefacts

on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

jobs:
  check_changes_in_lib:
    runs-on: ubuntu-latest

    outputs:
      modified: ${{ steps.modified.outputs.modified }}

    steps:
      - id: modified
        uses: anna-money/action-check-changes@master
        with:
          path: ${{ inputs.app_dir }}/schema

  get_dev_tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.dev-tag.outputs.tag }}

    steps:
      - id: dev-tag
        uses: anna-money/workflow-bionic-beaver/.github/actions/get-dev-tag@20b7dd64205250f4872e59d4484103ce862967a1

  build_lib:
    runs-on: ubuntu-latest

    needs: [ check_changes_in_lib, get_dev_tag ]

    if: needs.check_changes_in_lib.outputs.modified > 0

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/build-python-package@20b7dd64205250f4872e59d4484103ce862967a1
        with:
          version: ${{ needs.get_dev_tag.outputs.tag }}
          version_path: ${{ inputs.app_dir }}/version.py
          setup_path: ${{ inputs.app_dir }}/schema
          pypi_repository: ${{ secrets.PYPI_HOST_DEV }}
          pypi_push_user: ${{ secrets.PYPI_PUSH_USERNAME }}
          pypi_push_password: ${{ secrets.PYPI_PUSH_PASSWORD }}
