name: Build dev artefacts

on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
      app_name:
        required: false
        type: string
      build_image:
        required: false
        type: boolean
        default: false
      build_lib:
        required: false
        type: boolean
        default: true
      dirty_tag:
        required: false
        type: boolean
        default: false
    outputs:
      tag:
        description: 'Version of the built application'
        value: ${{ jobs.get_dev_tag.outputs.tag }}

jobs:
  check_changes_in_lib:
    runs-on: ubuntu-latest
    if: ${{ inputs.build_lib }}

    outputs:
      modified: ${{ steps.modified.outputs.modified }}

    steps:
      - id: modified
        uses: anna-money/action-check-changes@master
        with:
          path: ${{ inputs.app_dir }}/schema

  get_dev_tag:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.dev-tag.outputs.tag }}

    steps:
      - id: dev-tag
        uses: anna-money/workflow-bionic-beaver/.github/actions/get-dev-tag@master

  build_lib:
    runs-on: ubuntu-latest
    needs: [ check_changes_in_lib, get_dev_tag ]
    if: ${{ inputs.build_lib && needs.check_changes_in_lib.outputs.modified > 0 }}

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/build-python-package@master
        with:
          version: ${{ needs.get_dev_tag.outputs.tag }}
          version_path: ${{ inputs.app_dir }}/version.py
          setup_path: ${{ inputs.app_dir }}/schema
          pypi_repository: ${{ secrets.PYPI_HOST_DEV }}
          pypi_push_user: ${{ secrets.PYPI_PUSH_USERNAME }}
          pypi_push_password: ${{ secrets.PYPI_PUSH_PASSWORD }}

  build_image:
    runs-on: ubuntu-latest
    needs: get_dev_tag
    if: ${{ inputs.build_image }}

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/build-python-image@master
        with:
          name: ${{ inputs.app_name }}
          version: ${{ needs.get_dev_tag.outputs.tag }}
          registry: ${{ secrets.DOCKER_REGISTY }}
          gcloud_service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
          pypi_user: ${{ secrets.PYPI_USER }}
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
          dirty_tag: ${{ inputs.dirty_tag }}
          mark_latest: false
