name: Check application

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.11"
      postgres_version:
        required: false
        type: string
        default: "14-alpine"
      rabbitmq_version:
        required: false
        type: string
        default: "3-management-alpine"
      mongo_version:
        required: false
        type: string
        default: "4.4.18"

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    services:
#      postgres:
#        image: postgres:${{ inputs.postgres_version }}
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: test_database
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
      rmq:
        image: rabbitmq:${{ inputs.rabbitmq_version }}
        ports:
          - 5672:5672
      mongo:
        image: mongo:${{ inputs.mongo_version }}
        ports:
          - 27017:27017
    steps:
      - name: Start PostgreSQL ${{ inputs.postgres_version }}
        shell: bash
        run: >
          docker run -d
          -p 5432:5432 
          -e POSTGRES_DB=test_database 
          -e POSTGRES_PASSWORD=postgres 
          postgres:${{ inputs.postgres_version }} 
          postgres
          -c fsync=off 
          -c full_page_writes=off 
          -c synchronous_commit=off 
          -c bgwriter_lru_maxpages=0 
          -c jit=off
      - uses: anna-money/workflow-bionic-beaver/.github/actions/test-python-app@master
        with:
          python_version: ${{ inputs.python_version }}
          pypi_user: ${{ secrets.PYPI_USER }}
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
          rmq_hosts: 127.0.0.1:5672
          postgres_host: 127.0.0.1
          postgres_password: postgres
          postgres_db_name: test_database
          mongo_connection_string: mongodb://127.0.0.1:27017
          mongo_db_name: test_database


  pre-commit:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - uses: anna-money/workflow-bionic-beaver/.github/actions/pre-commit@master
        with:
          python_version: ${{ inputs.python_version }}
          pypi_user: ${{ secrets.PYPI_USER }}
          pypi_password: ${{ secrets.PYPI_PASSWORD }}
